name: Check & fix styling

on:
  push:

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run prettier
        uses: docker://permafrostsoftware/prettier-docker-ga
        with:
          args: --config prettier.config.js *.js *.json *.yml ./src/* ./tests/*

      - name: Run ESLint
        uses: permafrost-dev/eslint-docker-ga@main
        with:
          args: --config .eslintrc.js --fix --ext ts,js ./src/**/* ./tests/**/*

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix styling
